/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bienvenidos_github_java;

import javax.swing.JOptionPane;

/**
 *
 * @author AndresFelipe
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        LBienvenido.setVisible(false);
        LNombreBienvenido.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LNombre = new javax.swing.JLabel();
        BSaludo = new javax.swing.JButton();
        ENombre = new javax.swing.JTextField();
        LBienvenido = new javax.swing.JLabel();
        LNombreBienvenido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LNombre.setText("Nombre:");

        BSaludo.setText("Saludo");
        BSaludo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BSaludoMouseClicked(evt);
            }
        });

        LBienvenido.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        LBienvenido.setForeground(new java.awt.Color(51, 204, 0));
        LBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBienvenido.setText("Bienvenid@");

        LNombreBienvenido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LNombreBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LNombreBienvenido.setText("Tu");
        LNombreBienvenido.setAlignmentY(0.0F);

        jLabel1.setText("Andres");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(LNombreBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ENombre))
                .addGap(18, 18, 18)
                .addComponent(BSaludo))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNombre)
                    .addComponent(BSaludo)
                    .addComponent(ENombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(LBienvenido)
                .addGap(28, 28, 28)
                .addComponent(LNombreBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        LNombre.getAccessibleContext().setAccessibleName("LNombre");
        BSaludo.getAccessibleContext().setAccessibleName("BSaludo");
        ENombre.getAccessibleContext().setAccessibleName("ENombre");
        LBienvenido.getAccessibleContext().setAccessibleName("LBienvenido");
        LNombreBienvenido.getAccessibleContext().setAccessibleName("LNombreBienvenido");
        LNombreBienvenido.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSaludoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSaludoMouseClicked
        LBienvenido.setVisible(true);
        LNombreBienvenido.setVisible(true);
        String SaludoBienvenida = ENombre.getText();
        LNombreBienvenido.setText(SaludoBienvenida);
        ENombre.setText("");
    }//GEN-LAST:event_BSaludoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JOptionPane.showMessageDialog(this, "Iniciando la aplicación");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSaludo;
    private javax.swing.JTextField ENombre;
    private javax.swing.JLabel LBienvenido;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LNombreBienvenido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
